"""empty message

Revision ID: e9a65ba4470f
Revises: 
Create Date: 2024-04-10 11:25:22.078739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9a65ba4470f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commodity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billNumber', sa.String(length=255), nullable=False),
    sa.Column('startDat', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('productInfo', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('通过', '未通过'), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=False),
    sa.Column('money', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Purchasing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billNumber', sa.String(length=255), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('productInfo', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('purchasingagent', sa.String(length=255), nullable=False),
    sa.Column('money', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_add',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_name', sa.String(length=255), nullable=False),
    sa.Column('users_name', sa.String(length=255), nullable=False),
    sa.Column('customer_type', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('purchasing')
    op.drop_table('user_add')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_add',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('users_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('customer_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('purchasing',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('billNumber', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('startDate', sa.DATE(), nullable=False),
    sa.Column('endDate', sa.DATE(), nullable=False),
    sa.Column('productInfo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchasingagent', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('money', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('User_add')
    op.drop_table('Purchasing')
    op.drop_table('Commodity')
    # ### end Alembic commands ###
